version: '3'

services:
  tepid-server:
    build: ./tomcat
    volumes:
      - ./tomcat/config:/etc/tepid
    ports:
      - 80

  couchdb:
    build: ./couchdb
    volumes:
      - ./couchdb/config:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
