version: '3'

services:

  couchdb:
    build: ./couchdb
    volumes:
      - ./couchdb/config:/opt/couchdb/etc/local.d
    ports:
      - 5984

  tepid-server:
    build: ./tomcat
    volumes:
      - ./tomcat/config:/etc/tepid
      - war:/usr/local/tomcat/webapps
    ports:
      - 8080
      - 8443

  tepid-web:
    build: ./web
    ports:
      - 443

  gitlab-runner:
    container_name: CI
    build: ./CI
    volumes:
      - war:/var/lib/tomcat8/webapps/
    environment:
      - GRADLE_VERSION=4.10
    tty: true

volumes:
  war:
