version: '3.5'

services:
  db:
    build: ./postgresql
    restart: unless-stopped
    env_file: db.env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  tepid-server:
    depends_on:
      - db
    build: ./tomcat
    volumes:
      - ./tomcat/config:/etc/tepid
      - war:/usr/local/tomcat/webapps
    ports:
      - 8080
      - 8443
    restart: unless-stopped

  build:
    depends_on:
      - db
    build: ./gradle
    volumes:
      - ./tomcat/config:/etc/tepid
      - war:/var/lib/tomcat8/webapps
    restart: "no"

  tepid-web:
    build: ./web
    ports:
      - 443
    restart: unless-stopped

  ci:
    build: ./gitlab-runner
    volumes:
      - war:/var/lib/tomcat8/webapps
      - ./tomcat/config:/etc/tepid
    environment:
      - GRADLE_VERSION=4.10
    tty: true
    restart: unless-stopped


volumes:
  war:
