version: '3'

services:

  couchdb:
    build: ./couchdb
    volumes:
      - ./couchdb/config:/opt/couchdb/etc/local.d
#      - ./couchdb/data:/opt/couchdb/data
    ports:
      - 5984
    restart: unless-stopped

  tepid-server:
    depends_on:
      - couchdb
    build: ./tomcat
    volumes:
      - ./tomcat/config:/etc/tepid
      - war:/usr/local/tomcat/webapps
    ports:
      - 8080
      - 8443
    restart: unless-stopped

  build:
    depends_on:
      - couchdb
    build: ./gradle
    volumes:
      - ./tomcat/config:/etc/tepid
      - war:/var/lib/tomcat8/webapps
    restart: "no"

  tepid-web:
    build: ./web
    ports:
      - 443
    restart: unless-stopped

  ci:
    build: ./gitlab-runner
    volumes:
      - war:/var/lib/tomcat8/webapps
      - ./tomcat/config:/etc/tepid
    environment:
      - GRADLE_VERSION=4.10
    tty: true
    restart: unless-stopped


volumes:
  war:
