version: '3'

services:

  couchdb:
    build: ./couchdb
    volumes:
      - ./couchdb/config:/opt/couchdb/etc/local.d
    ports:
      - 5984

  tepid-server:
    build: ./tomcat
    volumes:
      - ./tomcat/config:/etc/tepid
    ports:
      - 8080
      - 8443

  tepid-web:
    build: ./web
    ports:
      - 443

  gitlab-runner:
    build: ./CI
    volumes:
      - ./CI/config:/etc/gitlab-runner/config
    environment:
      - GRADLE_VERSION=4.10
